version: '3.8'

services:
  app:
    build: .
    container_name: iot_backend_api
    ports:
      - "8000:8000"  # Expose the FastAPI app on port 8000
    environment:
      - DATABASE_URL=postgresql://clau:c123456@localhost:5432/dtlabs?sslmode=disable
      - SECRET_KEY=your-secret-key
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - iot_network
  
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: clau
      POSTGRES_PASSWORD: c123456
      POSTGRES_DB: dtlabs
    ports:
      - "5432:5432"
    networks:
      - iot_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  iot_network:
    driver: bridge